server:
  port: 58083
spring:
  application:
    name: canal
  redis:
    host: 10.177.73.40
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:57001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
#canal配置
canal:
  client:
    instances:
      # example
      example:
        host: 10.177.73.40
        port: 11111